/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogIn;

import ConnectSQL.DataValidator;
import ConnectSQL.MessagaDialog;
import ConnectSQL.SharedData;
import Dialog.AboutUsJDialog;
import Model.UserData;
import View.ChaoMungJframe;
import View.Menu;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import qlba.DAO.UserDAO;

/**
 *
 * @author Quang Huy
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form logIn
     */
    public LogIn() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfUserid = new javax.swing.JTextField();
        jtfPassword = new javax.swing.JPasswordField();
        jbtLogin = new javax.swing.JButton();
        jbtCreateaccount = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQuyen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtfLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        jtfUserid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfPassword.setText("123456");
        jtfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPasswordActionPerformed(evt);
            }
        });

        jbtLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login-icon-16.png"))); // NOI18N
        jbtLogin.setText("Login");
        jbtLogin.setPreferredSize(new java.awt.Dimension(95, 30));
        jbtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLoginActionPerformed(evt);
            }
        });

        jbtCreateaccount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtCreateaccount.setForeground(new java.awt.Color(255, 255, 255));
        jbtCreateaccount.setText("Create Account ?");
        jbtCreateaccount.setContentAreaFilled(false);
        jbtCreateaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCreateaccountActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LogIn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quyền Truy Cập");

        txtQuyen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhan Viên Kham Benh", "Nhan Vien Quan Ly Ho So", "Can Bo Phong Ban", "" }));
        txtQuyen.setSelectedIndex(-1);
        txtQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuyenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jbtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(jtfPassword)
                    .addComponent(jtfUserid)
                    .addComponent(txtQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jbtCreateaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfUserid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jbtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jbtCreateaccount)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jtfLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DangNhap5.PNG"))); // NOI18N
        jtfLogo.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jtfLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPasswordActionPerformed

    private void jbtCreateaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCreateaccountActionPerformed
        DangKiJDialog dangki = new DangKiJDialog(this, true);

        dangki.setVisible(true);
    }//GEN-LAST:event_jbtCreateaccountActionPerformed

    private void jbtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLoginActionPerformed
        StringBuilder sb = new StringBuilder();      
        DataValidator.validateEmpty(jtfUserid, sb, "UserID không được để trống");
        DataValidator.validateEmpty(jtfPassword, sb, "Pasword không đựơc để trống");       
        
        if (sb.length() > 0) {
            MessagaDialog.showErrorDialog(this, sb.toString(), "Lỗi");
            return;
        }

        UserDAO dao = new UserDAO();
        try {
            UserData us = dao.checkLogin(jtfUserid.getText(), new String(jtfPassword.getPassword()), new String(txtQuyen.getSelectedItem().toString()));
            if (us == null) {
                MessagaDialog.showErrorDialog(this, "Thông Tin đăng nhập chưa chính xác !", "Lỗi");
            } else {
                Menu menu = new Menu();
                if(txtQuyen.getSelectedIndex()==0){
                    menu.jbtQuanLyBenhAn.setEnabled(false);
                    menu.jbtThongTinBA.setEnabled(false);
                    menu.mnuBenhAn.setEnabled(false);
                    menu.mnuThongTin.setEnabled(false);
                }
                if(txtQuyen.getSelectedIndex()==1){
                    menu.jbtLichKham.setEnabled(false );
                    menu.mnuLichKham.setEnabled(false);
                }
                
                SharedData.userNhap = us;
                setVisible(false);
                
                
                
                menu.setVisible(true);
                this.dispose();  
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessagaDialog.showErrorDialog(this, e.getMessage(), "Lỗi");
        }    
    }//GEN-LAST:event_jbtLoginActionPerformed

    private void txtQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtCreateaccount;
    private javax.swing.JButton jbtLogin;
    private javax.swing.JLabel jtfLogo;
    private javax.swing.JPasswordField jtfPassword;
    private javax.swing.JTextField jtfUserid;
    public javax.swing.JComboBox<String> txtQuyen;
    // End of variables declaration//GEN-END:variables
}
