/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ConnectSQL.SharedData;
import Dialog.CaNhanJDialog;
import Dialog.AboutUsJDialog;
import Dialog.LichTrucJDialog;
import LogIn.LogIn;
import Model.ThongKe;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.apache.commons.math3.stat.descriptive.moment.Mean;

/**
 *
 * @author Quang Huy
 */
public class Menu extends javax.swing.JFrame {

    private QuanLyBenhAnPanel mBenhAnPanel;         // Đối tượng thể hiện của Panel
    private ThongTinBenhAnPanel mThongTinPanel;
    private DatLichKhamPanel mDatLich;
    private ThongKePanel mThongKe;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        setLocationRelativeTo(null);
        showtime();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
       
    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                SimpleDateFormat D = new SimpleDateFormat("dd/MM/yyyy");
                lblTime.setText(s.format(d) + "-" + D.format(d));
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jbtLogout = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jbtLichKham = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jbtQuanLyBenhAn = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jbtThongTinBA = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbtGioiThieu = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        jtbMainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnLichTruc = new javax.swing.JMenu();
        jmnProfile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmnThongBao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmnLichtruc = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuTTBenhAn = new javax.swing.JMenu();
        mnuBenhAn = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuThongTin = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuLichKham = new javax.swing.JMenuItem();
        jmnExit = new javax.swing.JMenu();
        jmnLogout = new javax.swing.JMenuItem();
        jmnexit = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bệnh Án - Lê Quang Huy 20IT268");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator11);

        jbtLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon-48.png"))); // NOI18N
        jbtLogout.setText("LogOut");
        jbtLogout.setFocusable(false);
        jbtLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtLogout.setPreferredSize(new java.awt.Dimension(200, 70));
        jbtLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtLogout);
        jToolBar1.add(jSeparator7);

        jbtLichKham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtLichKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lich.png"))); // NOI18N
        jbtLichKham.setText("Đặt Lịch Khám");
        jbtLichKham.setFocusable(false);
        jbtLichKham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtLichKham.setPreferredSize(new java.awt.Dimension(160, 61));
        jbtLichKham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtLichKham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLichKhamActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtLichKham);
        jToolBar1.add(jSeparator13);

        jbtQuanLyBenhAn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtQuanLyBenhAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLBA1.png"))); // NOI18N
        jbtQuanLyBenhAn.setText("Quản Lý Bệnh Án");
        jbtQuanLyBenhAn.setFocusable(false);
        jbtQuanLyBenhAn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtQuanLyBenhAn.setPreferredSize(new java.awt.Dimension(200, 70));
        jbtQuanLyBenhAn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtQuanLyBenhAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQuanLyBenhAnActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtQuanLyBenhAn);
        jToolBar1.add(jSeparator8);

        jbtThongTinBA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtThongTinBA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TTBA.png"))); // NOI18N
        jbtThongTinBA.setText("Thông Tin Chi tiết Bệnh Án");
        jbtThongTinBA.setFocusable(false);
        jbtThongTinBA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtThongTinBA.setPreferredSize(new java.awt.Dimension(200, 70));
        jbtThongTinBA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtThongTinBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThongTinBAActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtThongTinBA);
        jToolBar1.add(jSeparator9);

        jButton1.setText("Thông Kê");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator3);

        jbtGioiThieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-help-about-icon-32_1.png"))); // NOI18N
        jbtGioiThieu.setText(" Giới Thiệu");
        jbtGioiThieu.setFocusable(false);
        jbtGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtGioiThieu.setPreferredSize(new java.awt.Dimension(200, 70));
        jbtGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtGioiThieu);

        lblTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon_clock.png"))); // NOI18N
        jToolBar1.add(lblTime);

        jmnLichTruc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/round_menu_black_18dp.png"))); // NOI18N
        jmnLichTruc.setText("Danh Mục");
        jmnLichTruc.setPreferredSize(new java.awt.Dimension(120, 40));

        jmnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ca nhan.png"))); // NOI18N
        jmnProfile.setText("Cá Nhân");
        jmnProfile.setPreferredSize(new java.awt.Dimension(300, 50));
        jmnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnProfileActionPerformed(evt);
            }
        });
        jmnLichTruc.add(jmnProfile);
        jmnLichTruc.add(jSeparator2);

        jmnThongBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thong bao.png"))); // NOI18N
        jmnThongBao.setText("Thông Báo");
        jmnThongBao.setPreferredSize(new java.awt.Dimension(300, 50));
        jmnThongBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnThongBaoActionPerformed(evt);
            }
        });
        jmnLichTruc.add(jmnThongBao);
        jmnLichTruc.add(jSeparator1);

        jmnLichtruc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lich truc.png"))); // NOI18N
        jmnLichtruc.setText("Lịch trực");
        jmnLichtruc.setPreferredSize(new java.awt.Dimension(300, 50));
        jmnLichtruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnLichtrucActionPerformed(evt);
            }
        });
        jmnLichTruc.add(jmnLichtruc);
        jmnLichTruc.add(jSeparator6);

        jMenuBar1.add(jmnLichTruc);

        mnuTTBenhAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-view-choose-icon-24.png"))); // NOI18N
        mnuTTBenhAn.setText("Quản Lý");
        mnuTTBenhAn.setMinimumSize(new java.awt.Dimension(170, 40));
        mnuTTBenhAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTTBenhAnActionPerformed(evt);
            }
        });

        mnuBenhAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLBA.png"))); // NOI18N
        mnuBenhAn.setText("Quản Lý Bệnh Án");
        mnuBenhAn.setPreferredSize(new java.awt.Dimension(300, 50));
        mnuBenhAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBenhAnActionPerformed(evt);
            }
        });
        mnuTTBenhAn.add(mnuBenhAn);
        mnuTTBenhAn.add(jSeparator4);

        mnuThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Thong tin bA.png"))); // NOI18N
        mnuThongTin.setText(" Thông Tin Chi Tiết Bệnh Án");
        mnuThongTin.setPreferredSize(new java.awt.Dimension(300, 50));
        mnuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThongTinActionPerformed(evt);
            }
        });
        mnuTTBenhAn.add(mnuThongTin);
        mnuTTBenhAn.add(jSeparator5);

        mnuLichKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lich.png"))); // NOI18N
        mnuLichKham.setText("Đặt Lịch Khám");
        mnuLichKham.setPreferredSize(new java.awt.Dimension(300, 50));
        mnuLichKham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLichKhamActionPerformed(evt);
            }
        });
        mnuTTBenhAn.add(mnuLichKham);

        jMenuBar1.add(mnuTTBenhAn);

        jmnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-help-about-icon-32.png"))); // NOI18N
        jmnExit.setText("Trợ Giúp");
        jmnExit.setPreferredSize(new java.awt.Dimension(100, 40));
        jmnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnExitActionPerformed(evt);
            }
        });

        jmnLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout-icon-16.png"))); // NOI18N
        jmnLogout.setText(" Logout");
        jmnLogout.setPreferredSize(new java.awt.Dimension(250, 40));
        jmnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnLogoutActionPerformed(evt);
            }
        });
        jmnExit.add(jmnLogout);

        jmnexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jmnexit.setText("Exit");
        jmnexit.setPreferredSize(new java.awt.Dimension(250, 40));
        jmnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnexitActionPerformed(evt);
            }
        });
        jmnExit.add(jmnexit);

        jMenuBar1.add(jmnExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
            .addComponent(jtbMainBoard)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnThongBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnThongBaoActionPerformed
        JOptionPane.showConfirmDialog(this, "Bạn chưa nhận được thông báo mới", "Thông báo", JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_jmnThongBaoActionPerformed

    private void mnuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThongTinActionPerformed
        if (mThongTinPanel == null) {

            mThongTinPanel = new ThongTinBenhAnPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/QLBA.png"));  //

            jtbMainBoard.addTab("THÔNG TIN BỆNH ÁN", icon, mThongTinPanel, "THÔNG TIN BỆNH ÁN");
        }
        jtbMainBoard.setSelectedComponent(mThongTinPanel);
    }//GEN-LAST:event_mnuThongTinActionPerformed

    private void jbtThongTinBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThongTinBAActionPerformed
        if (mThongTinPanel == null) {

            mThongTinPanel = new ThongTinBenhAnPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/QLBA.png"));

            jtbMainBoard.addTab("THÔNG TIN BỆNH ÁN", icon, mThongTinPanel, "THÔNG TIN BỆNH ÁN");
        }
        jtbMainBoard.setSelectedComponent(mThongTinPanel);
    }//GEN-LAST:event_jbtThongTinBAActionPerformed

    private void jmnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnExitActionPerformed

    private void jmnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnexitActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jmnexitActionPerformed

    private void mnuBenhAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBenhAnActionPerformed
        if (mBenhAnPanel == null) {

            mBenhAnPanel = new QuanLyBenhAnPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/QLBA.png"));

            jtbMainBoard.addTab("QUẢN LÝ BỆNH ÁN", icon, mBenhAnPanel, "QUẢN LÝ BỆNH ÁN");
        }
        jtbMainBoard.setSelectedComponent(mBenhAnPanel);


    }//GEN-LAST:event_mnuBenhAnActionPerformed

    private void mnuTTBenhAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTTBenhAnActionPerformed

    }//GEN-LAST:event_mnuTTBenhAnActionPerformed

    private void jbtGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGioiThieuActionPerformed
        AboutUsJDialog aboutDialog = new AboutUsJDialog(this, true);

        aboutDialog.setVisible(true);
    }//GEN-LAST:event_jbtGioiThieuActionPerformed

    private void jmnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnLogoutActionPerformed
        setVisible(false);

        new LogIn().setVisible(true);

    }//GEN-LAST:event_jmnLogoutActionPerformed

    private void jbtLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLogoutActionPerformed
        setVisible(false);

        new LogIn().setVisible(true);
    }//GEN-LAST:event_jbtLogoutActionPerformed

    private void jbtQuanLyBenhAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQuanLyBenhAnActionPerformed
        if (mBenhAnPanel == null) {

            mBenhAnPanel = new QuanLyBenhAnPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/QLBA.png"));
            
            jtbMainBoard.addTab("QUẢN LÝ BỆNH ÁN", icon, mBenhAnPanel, "QUẢN LÝ BỆNH ÁN");
        }
        jtbMainBoard.setSelectedComponent(mBenhAnPanel);
    }//GEN-LAST:event_jbtQuanLyBenhAnActionPerformed

    private void jmnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnProfileActionPerformed
        CaNhanJDialog canhan = new CaNhanJDialog(this, true);

        canhan.setVisible(true);
    }//GEN-LAST:event_jmnProfileActionPerformed

    private void mnuLichKhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLichKhamActionPerformed
        if (mDatLich == null) {

            mDatLich = new DatLichKhamPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/Lich.png"));

            jtbMainBoard.addTab("ĐẶT LỊCH KHÁM", icon, mDatLich, "ĐẶT LICH KHÁM");
        }
        jtbMainBoard.setSelectedComponent(mDatLich);
    }//GEN-LAST:event_mnuLichKhamActionPerformed

    private void jmnLichtrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnLichtrucActionPerformed
        LichTrucJDialog lichtruc = new LichTrucJDialog(this, true);

        lichtruc.setVisible(true);
    }//GEN-LAST:event_jmnLichtrucActionPerformed

    private void jbtLichKhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLichKhamActionPerformed
        if (mDatLich == null) {

            mDatLich = new DatLichKhamPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/Lich.png"));

            jtbMainBoard.addTab("ĐẶT LỊCH KHÁM", icon, mDatLich, "ĐẶT LICH KHÁM");
        }

    }//GEN-LAST:event_jbtLichKhamActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int nutbam = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thoát ?", "THOÁT", JOptionPane.OK_CANCEL_OPTION);
        if (nutbam == JOptionPane.OK_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (mThongKe == null) {

            mThongKe = new ThongKePanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/Lich.png"));

            jtbMainBoard.addTab("THÔNG KÊ", icon, mThongKe, "THỐNG KÊ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                ChaoMungJframe x = new ChaoMungJframe() ;
//                x.setVisible(true);
//                try{
//                    Thread.sleep(2000);
//                }catch(Exception e){
//                    e.printStackTrace();
//                }
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtGioiThieu;
    public javax.swing.JButton jbtLichKham;
    private javax.swing.JButton jbtLogout;
    public javax.swing.JButton jbtQuanLyBenhAn;
    public javax.swing.JButton jbtThongTinBA;
    private javax.swing.JMenu jmnExit;
    private javax.swing.JMenu jmnLichTruc;
    private javax.swing.JMenuItem jmnLichtruc;
    private javax.swing.JMenuItem jmnLogout;
    private javax.swing.JMenuItem jmnProfile;
    private javax.swing.JMenuItem jmnThongBao;
    private javax.swing.JMenuItem jmnexit;
    private javax.swing.JTabbedPane jtbMainBoard;
    private javax.swing.JLabel lblTime;
    public javax.swing.JMenuItem mnuBenhAn;
    public javax.swing.JMenuItem mnuLichKham;
    private javax.swing.JMenu mnuTTBenhAn;
    public javax.swing.JMenuItem mnuThongTin;
    // End of variables declaration//GEN-END:variables
}
